---
title: "EDS223: Week 1 Lab"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}
install.packages('sf') #vector data
install.packages("stars") #raster data
install.packages("tmap") # map making
#install.packages("here") #file paths
```

```{r}
library(sf)
library(stars)
library(tmap)
library(here)
```

```{r}
world_elevation <- read_stars(here("data","worldelevation.tif"))

world_vector<- read_sf(here("data","worldvector.gpkg"))

world_cities<-read_sf(here("data","worldcities.gpkg"))

```


```{r}
tm_shape(world_elevation) + 
  tm_raster()+
tm_shape(world_vector) + 
  tm_borders() + 
  tm_shape(world_cities, is.master=TRUE) +
  tm_dots() 
```

```{r}
tm_shape(world_vector)+
  tm_polygons(col= "lightblue",
              border.col = "black",
              lwd=0.5, #linewidth
              lty="dashed") #linetype
```
```{r}
tm_shape(world_vector)+
  tm_borders(col="red")
```
```{r}
tm_shape(world_vector)+
  tm_fill(col="lightblue")
```

```{r}
tm_shape(world_vector)+
  tm_fill("CO2_emissions")
```

```{r}
tm_shape(world_cities)+
  tm_dots()
```

```{r}
tm_shape(world_vector)+
  tm_polygons("life_expectancy",
              palette= c("yellow","darkgreen"),
              title="Life Expectancy (Years)")
```

```{r}
install.packages("viridisLite")
library("viridisLite")
```

```{r}
tm_shape(world_vector)+
  tm_polygons("life_expectancy",
              palette= viridis(option="plasma",8),
              title="Life Expectancy (Years)")
```

```{r}
tm_shape(world_vector)+
  tm_polygons()+
  tm_shape(world_cities)+
  tm_symbols(size="pop2020",
             legend.size.is.portrait = TRUE)
```

```{r}
tm_shape(world_vector)+
  tm_fill()+
  tm_grid() #tm_graticules to change to lat/lot
```

```{r}
tm_shape(world_vector)+
  tm_fill()+
  tm_scale_bar()+
  tm_compass(position=c("left","top"))
```

```{r}
tmap_mode("view")

tm_shape(world_vector)+
  tm_fill(col = "wb_income_region",
          palette=viridisLite::plasma(5),
          title="Regional Income")+
  tm_layout(bg.color="grey95",
            main.title="Global income by country",
            frame=FALSE)
  
```

```{r}
tmap_mode("plot") #back to go static map

#save
map1<-tm_shape(world_vector)+
  tm_fill(col = "wb_income_region",
          palette=viridisLite::plasma(5),
          title="Regional Income")+
  tm_layout(bg.color="grey95",
            main.title="Global income by country",
            frame=FALSE)

tmap_save(map1,here("tmap-example.png"))
```

